//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tonneru.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tonneru.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string other_preferences {
            get {
                return ResourceManager.GetString("other.preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support me on Ko-fi.
        /// </summary>
        public static string preferences_donate {
            get {
                return ResourceManager.GetString("preferences.donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View source code on GitHub.
        /// </summary>
        public static string preferences_github {
            get {
                return ResourceManager.GetString("preferences.github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an issue.
        /// </summary>
        public static string preferences_issue {
            get {
                return ResourceManager.GetString("preferences.issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string preferences_language {
            get {
                return ResourceManager.GetString("preferences.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License.
        /// </summary>
        public static string preferences_license {
            get {
                return ResourceManager.GetString("preferences.license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more of my software on prefex.dev.
        /// </summary>
        public static string preferences_more {
            get {
                return ResourceManager.GetString("preferences.more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string preferences_theme {
            get {
                return ResourceManager.GetString("preferences.theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add profile.
        /// </summary>
        public static string profiles_add {
            get {
                return ResourceManager.GetString("profiles.add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        public static string profiles_clear {
            get {
                return ResourceManager.GetString("profiles.clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove profile.
        /// </summary>
        public static string profiles_remove {
            get {
                return ResourceManager.GetString("profiles.remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-Click to create or delete profiles.
        /// </summary>
        public static string profiles_rightclick {
            get {
                return ResourceManager.GetString("profiles.rightclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save profile.
        /// </summary>
        public static string profiles_save {
            get {
                return ResourceManager.GetString("profiles.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string status_active {
            get {
                return ResourceManager.GetString("status.active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string status_connecting {
            get {
                return ResourceManager.GetString("status.connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string status_disconnected {
            get {
                return ResourceManager.GetString("status.disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string status_error {
            get {
                return ResourceManager.GetString("status.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string status_waiting {
            get {
                return ResourceManager.GetString("status.waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string tunnel_host {
            get {
                return ResourceManager.GetString("tunnel.host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local host.
        /// </summary>
        public static string tunnel_local_host {
            get {
                return ResourceManager.GetString("tunnel.local.host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local port.
        /// </summary>
        public static string tunnel_local_port {
            get {
                return ResourceManager.GetString("tunnel.local.port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string tunnel_password {
            get {
                return ResourceManager.GetString("tunnel.password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string tunnel_port {
            get {
                return ResourceManager.GetString("tunnel.port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote host.
        /// </summary>
        public static string tunnel_remote_host {
            get {
                return ResourceManager.GetString("tunnel.remote.host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote port.
        /// </summary>
        public static string tunnel_remote_port {
            get {
                return ResourceManager.GetString("tunnel.remote.port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string tunnel_username {
            get {
                return ResourceManager.GetString("tunnel.username", resourceCulture);
            }
        }
    }
}
